from ..project import ADMIN_EMAIL, PROJECT_PREFIX


DEBUG = False

# Flask-Mail
MAIL_DEFAULT_SENDER = ADMIN_EMAIL

# Flask-Cache
CACHE_KEY_PREFIX = PROJECT_PREFIX + ":"
CACHE_NO_NULL_WARNING = True

# Flask-SQLAlchemy
SQLALCHEMY_TRACK_MODIFICATIONS = False
